import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="bg-blue-50 text-blue-600 text-xs text-center py-1 border-b font-mono font-medium flex justify-center gap-4">
          <span>Deploy Version: {process.env.NEXT_PUBLIC_APP_VERSION || 'local-dev'}</span>
          <span>Deployed: {process.env.NEXT_PUBLIC_DEPLOY_DATE || 'N/A'}</span>
        </div>
        {children}
      </body>
    </html>
  );
}
